spring:
  aop:
    proxy-target-class: true

  sleuth:
    sampler:
      percentage: 0.2 #日志的采样率



##  demo for  database connect ##
  datasource:
      url: jdbc:mysql://${MYSQL_HOST:${ENV_HOST}}:${MYSQL_PORT:3306}/${MYSQL_DB:estore_tenancydb}?autoReconnect=true&useAffectedRows=true&useSSL=${MYSQL_SSL:false}
      username: ${MYSQL_USER:root}
      password: ${MYSQL_PASSWORD:mysql123}
      driver-class-name: com.mysql.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource


logging:
  level:
    com.d1m.elasticsearch.repository: DEBUG
  ##config: classpath:logback-spring.xml
  path: /var/log/estore-scrm
mybatis:
  type-aliases-package: com.d1m.elasticsearch.domain.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


